services:
  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: Hello@123
      MYSQL_DATABASE: MANY_Vinato-db
    ports:
      - "3307:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-pHello@123"]
      interval: 10s
      timeout: 5s
      retries: 5

  web:
    build: .
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "80:80"
      - "8081:8080"
      - "2222:22"

  web2:
    build: .
    depends_on:
      db:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: noseed
    ports:
      - "2223:22"

  lb:
    build: .
    volumes:
      - ./nginx-lb.conf:/etc/nginx/sites-available/default
    entrypoint: ["/bin/bash", "-c", "service ssh start && nginx -g 'daemon off;'"]
    depends_on:
      - web
      - web2
    ports:
      - "8090:80"
      - "2224:22"
